---
services:
  crayfish_commons_syn.settings_parser:
    public: false
    class: Islandora\Crayfish\Commons\Syn\SettingsParser
    constructor: create
    arguments:
      - "assets/default_syn.xml"
  crayfish_commons_syn.jwt.factory:
    public: false
    class: Islandora\Crayfish\Commons\Syn\JwtFactory
  crayfish_commons_syn.jwt.authenticator:
    public: true
    class: Islandora\Crayfish\Commons\Syn\JwtAuthenticator
    arguments:
      - '@crayfish_commons_syn.settings_parser'
      - '@crayfish_commons_syn.jwt.factory'
